league/models/User.php
<?php

class User extends ActiveRecord implements IdentityInterface
{	
	const ROLE_USER = 0;
	const ROLE_ADMIN = 1;
	
	const AVATAR_SIZE = 400;
	const AVATAR_PATH = 'C:/xampp/htdocs/gorion/league/site/img/avatars/';
	
	const SCENARIO_SIGNUP = 'signup';
	const SCENARIO_LOGIN = 'login';
	const SCENARIO_PAIR = 'pair';
	const SCENARIO_EDIT = 'edit';
	
	const POSITION_TOP = 0;
	const POSITION_MID = 2;
	const POSITION_JUNGLE = 1;
	const POSITION_SUPPORT = 3;
	const POSITION_ADC = 4;
	const POSITION_TBD = 5;
	
	const CLEAR = ['role', 'isVerified', 'isMember', 'avatar', 'teamId', 'tier', 'division', 'summonerId'];
	
	function attributeLabels()
	{
		return [
			'username' => 'Login',
			'password' => 'Hasło',
			'firstName' => 'Imię',
			'lastName' => 'Nazwisko',
			'summonerName' => 'Nazwa przywoływacza',
			'name' => 'Imię i nazwisko',
			'school' => 'Szkoła',
		];
	}
	
	function rules()
	{
		switch ($this->scenario)
		{
			case self::SCENARIO_SIGNUP: return [
				'username' => [
					'required', 
					['string', 'length' => ['max' => 30, 'min' => 3]], 
					['unique', 'field' => 'username', 'msg' => 'Ta nazwa jest zajęta']
				], 
				'email' => [
					'required', 
					'email', 
					['unique', 'field' => 'email', 'msg' => 'Ten email jest już w użyciu']
				], 
				'password' => [
					'required', 
					['string', 'length' => ['max' => 35, 'min' => 5]]
				],
				'firstName' => [
					'required', 
					['string', 'length' => ['max' => 35, 'min' => 5]]
				],
				'lastName' => [
					'required', 
					['string', 'length' => ['max' => 35, 'min' => 5]]
				],
				'school' => [['required']],
			];
			case self::SCENARIO_EDIT: return [
				'firstName' => ['required', ['string', 'length' => ['max' => 35, 'min' => 5]]],
				'lastName' => ['required', ['string', 'length' => ['max' => 35, 'min' => 5]]],
				'school' => [['required']],
			];
			case self::SCENARIO_LOGIN: return ['username' => ['required'], 'password' => ['required']];
			case self::SCENARIO_PAIR: return ['summonerName' => ['required']];
		}
	}
	
	function updateRank()
	{
		if ($this->summonerId)
		{
			$league = App::lolAPI('league-entry', $this->summonerId);
			if ($league == 404)
			{
				$this->tier = 'provisional';
			}
			else
			{
				$this->tier = strtolower($league[0]->tier);
				$this->division = strtolower($league[0]->entries[0]->division);
			}
			$this->update();
		}
	}
	
	function getFullName()
	{
		return $this->firstName.' '.$this->lastName;
	}
	
	function getFullNameAndAlias()
	{
		return $this->firstName.' "'.$this->summonerName.'" '.$this->lastName;
	}
	
	function getTeam()
	{
		if (!$this->isMember) { return null; }
		return Team::findOne(['id' => $this->teamId]);
	}
	
	function getRequestedTeam()
	{
		if ($this->isMember) { return null; }
		return Team::findOne(['id' => $this->teamId]);
	}
	
	function getAvatarPath()
	{
		if ($this->hasAvatar)
		{
			return Url::img('avatars/'.$this->avatar, false);
		}
		else
		{
			if ($this->summonerId)
			{
				return "http://ddragon.leagueoflegends.com/cdn/6.14.2/img/profileicon/$this->profileIcon.png";
			}
			else
			{
				return Url::img('avatars/no_avatar.png', false);
			}
		}
	}
	
	function getHasAvatar()
	{
		return $this->avatar != 'no_avatar.png';
	}
	
	function getRankImage()
	{
		if ($this->tier)
		{
			if ($this->tier == 'provisional' || $this->tier == 'master' || $this->tier == 'challenger')
			{
				return "tier_icons/base_icons/$this->tier.png";
			}
			else
			{
				return "tier_icons/tier_icons/$this->tier"."_$this->division.png";
			}
		}
	}
	
	function getRank()
	{
		return TournamentHelper::calculateRank($this);
	}
	
	function login($password)
	{
		return password_verify($password, $this->password);
	}
}

league/controllers/UserController.php
<?php

class UserController extends BaseController
{
	function permissions()
	{
		return [
			'signup' => self::ACCESS_GUEST,
			'view' => self::ACCESS_GUEST,
		];
	}
	
	function actionSignup()
	{
		$model = new User(User::SCENARIO_SIGNUP);
		
		if ($model->load(App::$post))
		{
			if ($model->validate())
			{
				$model->password = password_hash($model->password, PASSWORD_DEFAULT);
				$model->teamId = 0;
				
				if ($model->save(false))
				{
					App::addFlash('success', 'Konto zostało utworzone. Możesz się teraz zalogować');
					return App::redirect(Url::to('site/login'));
				}
				
				App::addFlash('danger', 'Nie udało się utworzyć konta');
			}
			else
			{
				$model->flashErrors();
			}
		}
		
		return $this->render('user/signup');
	}
	
	function actionPair()
	{
		$model = new User(User::SCENARIO_PAIR);
		
		if (App::$user->summonerName)
		{
			App::addFlash('warning', 'Już sparowałeś swoje konto. Jeśli chcesz je zmienić, najpierw usuń poprzednie powiązanie.');
		}
		else
		{
			if ($model->load(App::$post))
			{
				$result = App::lolAPI('summoner-name', $model->summonerName);
				
				$summoner = App::lolAPI('summoner', $result->id);

				if ($result instanceof stdClass)
				{				
					if (User::find()->where(['summoner_name' => $result->name])->andWhere(['is_verified' => true])->one())
					{
						App::addFlash('warning', 'To konto zostało już przypisane. Jeśli uważasz, że ktoś przypisał Twoje konto, napisz do nas maila.');
					}
					else
					{
						$user = App::$user;
						
						$user->profileIcon = $summoner->profileIconId;
						$user->summonerName = $result->name;
						$user->summonerId = $result->id;

						if ($user->update(false))
						{
							App::addFlash('success', 'Twoje konto zostało sparowane. Zweryfikuj je teraz.');
							App::updateUser();
							App::$user->updateRank();
							App::updateUser();
							return App::redirect(Url::to(['user/edit', 'id' => App::$user->id]));
						}
						else
						{
							App::addFlash('danger', 'Nie udało się powiązać twojego konta.');
						}
					}
				}
				else if ($result == 404)
				{
					App::addFlash('danger', 'Nie istnieje taki przywoływacz.');
				}
			}
		}
		
		return $this->render('user/pair', ['user' => $model]);
	}
	
	function actionUnpair()
	{
		$user = App::$user;
		
		if ($user->team && $user->isMember)
		{
			App::addFlash('danger', 'Nie możesz rozłączyć konta, ponieważ jesteś członkiem drużyny. Opuść najpierw drużynę.');
		}
		else
		{
			$query = (new Query)->update(User::tableName(), ['summoner_name' => '', 'summoner_id' => 0, 'is_verified' => 0])->where(['id' => $user->id]);
			if ($query->run())
			{
				App::addFlash('success', 'Rozłączono twoje konto z League of Legends.');
				App::updateUser();
			}
			else
			{
				App::addFlash('danger', 'Nie udało się rozłączyć konta.');
			}
		}
		
		return App::redirect(Url::to(['user/edit', 'id' => $user->id]));
	}
	
	function actionView($id)
	{
		$model = User::findOne(['id' => $id]);
		
		if ($model === null)
		{
			App::addFlash('warning', 'Nie znaleziono strony');
			return App::goBack();
		}
		
		return $this->render('user/view', ['user' => $model]);
	}
	
	function actionEdit()
	{
		$model = App::$user;
		$model->scenario = User::SCENARIO_EDIT;
		
		if ($model->load(App::$post))
		{
			if ($model->update())
			{
				App::addFlash('success', "Zmiany zapisano.");
			}
			else
			{
				$model->flashErrors();
			}
			App::updateUser();
		}
		
		return $this->render('user/edit', ['user' => $model]);
	}
	
	function actionUpdateAvatar()
	{
		if (isset($_FILES['User:image']))
		{
			$file = App::fileUpload('User:image');
			
			if ($file)
			{
				$a = User::AVATAR_SIZE;
				
				$imagine = new \Imagine\Gd\Imagine;
				
				$image = $imagine->open($file);
				
				$size = $image->getSize();
				
				if ($size->getHeight() > $size->getWidth())
				{
					$newSize = new Imagine\Image\Box($a, $a * ($size->getHeight() / $size->getWidth()));
					$image->resize($newSize);
					
					$offset = ($newSize->getHeight() - $a) / 2;
					$image->crop(new Imagine\Image\Point(0, $offset), new Imagine\Image\Box($a, $a));
				}
				else if ($size->getHeight() < $size->getWidth())
				{
					$newSize = new Imagine\Image\Box($a, $a * ($size->getWidth() / $size->getHeight()));
					$image->resize($newSize);
					
					$offset = ($newSize->getWidth() - $a) / 2;
					$image->crop(new Imagine\Image\Point($offset, 0), new Imagine\Image\Box($a, $a));
				}
				else
				{
					$image->resize(new Imagine\Image\Box($a, $a));
				}
				
				$path = md5(App::$user->username.rand(0,1000)).'.jpg';
				if ($image->save(User::AVATAR_PATH.$path))
				{
					if ((new Query)->update(User::tableName(), ['avatar' => $path])->where(['id' => App::$user->id])->run())
					{
						unlink($file);
						App::addFlash('success', 'Awatar został zmieniony.');
						App::updateUser();
						return App::redirect(Url::to(['user/edit', 'id' => App::$user->id]));
					}
					else
					{
						App::addFlash('danger', 'Nie udało się połączyć z bazą danych.');
					}
				}
				else
				{
					App::addFlash('danger', 'Nie udało się zmienić awatara.');
				}
			}
		}
		
		return $this->render('user/uploadAvatar', ['user' => App::$user]);
	}
	
	function actionDeleteAvatar()
	{
		if (App::$user->avatar != 'no_avatar.png')
		{
			$path = App::$user->avatar;
			if ((new Query)->update(User::tableName(), ['avatar' => 'no_avatar.png'])->where(['id' => App::$user->id])->run())
			{
				unlink($path);
				App::addFlash('success', 'Usunięto awatar.');
				App::updateUser();
			}
			else
			{
				App::addFlash('danger', 'Nie udało się usunąć awatara.');
			}
		}
		return App::redirect(Url::to(['user/edit', 'id' => App::$user->id]));
	}
	
	function actionLeaveTeam()
	{
		$user = App::$user;
		$team = $user->team ?: $user->requestedTeam;
		
		if ($team)
		{
			if (!$team->isLocked)
			{
				if ($user->id == $team->ownerId)
				{
					$members = $team->members;

					if (count($members) == 1)
					{
						$user->teamId = null;
						$user->isMember = false;
						if($team->delete() && $user->update(false))
						{
							App::addFlash('success', 'Opuściłeś drużynę. Ponieważ byłeś jedynym jej członkiem, została usunięta.');
						}
					}
					else
					{
						$user->teamId = null;
						$user->isMember = false;
						if ($user->update(false))
						{
							$team = Team::findOne(['id' => $team->id]);
							$count = count($team->members);
							$newOwner = $team->members[rand(0, $count-1)];
							$team->ownerId = $newOwner->id;

							if ($team->update(false))
							{
								App::addFlash('success', "Opuściłeś drużynę. Ponieważ byłeś jej właścicielem, przekazano uprawnienia użytkownikowi $newOwner->summonerName");
							}
							else
							{
								App::addFlash('danger', 'Wystąpił błąd podczas połączenia z bazą danych');
							}
						}
						else
						{
							App::addFlash('danger', 'Wystąpił błąd podczas połączenia z bazą danych');
						}
					}
					App::updateUser();
				}
				else
				{
					$member = $user->isMember;
					$user->isMember = false;
					$user->teamId = null;
					if ($user->update(false))
					{
						App::addFlash('success', $member ? 'Opuściłeś drużynę' : 'Cofnięto prośbę');
						App::updateUser();
					}
					else
					{
						App::addFlash('danger', $member ? 'Nie udało się opuścić drużyny' : 'Nie udało się cofnąć prośby');
					}
				}
			}
			else
			{
				App::addFlash('danger', 'Ta drużyna jest zablokowana. Nie możesz jej opuścić. '.($user->id == $team->ownerId ? 'Odblokuj ją.' : 'Poproś właściciela, by odblokował drużynę.'));
			}
		}
		
		return App::goBack();
	}
	
	function actionVerify($done = false)
	{
		$user = App::$user;
		
		if (!$user->summonerName)
		{
			return App::goBack();
		}
		else
		{
			if ($user->isVerified)
			{
				App::addFlash('warning', 'Już zweryfikowałeś swoje konto');
				return App::goBack(0);
			}
			else
			{
				if ($done)
				{
					if (!$user->verificationKey)
					{
						goto generate;
					}
					else
					{
						$result = App::lolAPI('runes', $user->summonerId);
						$verified = false;
						foreach ($result->pages as $page)
						{
							if ($page->name == $user->verificationKey)
							{
								$verified = true;
							}
						}
						
						if ($verified)
						{
							$user->isVerified = true;
							if ($user->update(false))
							{
								App::addFlash('success', 'Twoje konto zostało zweryfikowane');
								App::updateUser();
								return App::goBack(1);
							}
							else
							{
								App::addFlash('danger', 'Wystąpił błąd');
							}
						}
						else
						{
							App::addFlash('warning', 'Nie zmieniłeś nazwy żadnej ze stron na runy');
						}
					}
				}
				else
				{
					generate:
					if (!$user->verificationKey)
					{
						$user->verificationKey = dechex(rand(0x11111111, 0xffffffff));
						$user->update();
						App::updateUser();
					}
				}	
			}
			return $this->render('user/verify', ['model' => $user]);
		}
	}
}

league/views/user/edit.php
<h1>Edycja profilu</h1>

<div class="row profile">
	
	<div class="col-lg-2 mb-3 mb-lg-0">
		
		<div class="avatar">
			
			<img src="<?= $user->avatarPath ?>" class="img-rounded"/>
			
			<div class="avatar-buttons">
			
				<?php if ($user->hasAvatar):

				echo Html::a(Url::to('user/deleteAvatar'), Html::fa('remove'), ['class' => 'btn btn-sm btn-danger'], false);
				echo Html::a(Url::to('user/updateAvatar'), Html::fa('pencil'), ['class' => 'btn btn-sm btn-warning'], false);
				
				else:
					
				echo Html::a(Url::to('user/updateAvatar'), Html::fa('plus'), ['class' => 'btn btn-sm btn-success'], false);

				endif; ?>
				
			</div>
			
		</div>
		
	</div>
	
	<div class="col-lg-10">
		
		<?php $form = new Form($user);
		
		echo $form->begin([
			'id' => 'user-edit-form',
			'class' => 'form-wide form-horizontal', 
			'layout' => [
				'label' => 'col-xs-2', 
				'field' => 'col-xs-10', 
				'offset' => 'col-xs-offset-2'
			]
		]);
		
		echo $form->field('firstName')->text();
		echo $form->field('lastName')->text();
		echo $form->field('school')->dropdown(App::$config['lo_list']);
		
		echo $form->end(true, Html::fa('save').' Zapisz zmiany');
		
		?>
		
		<div class="summoner <?= $user->summonerName ? ($user->isVerified ? '' : 'unverified') : 'inactive'?>"><?= Html::fa('gamepad', true).' '.($user->summonerName 
		? $user->summonerName.Html::a(Url::to(['user/unpair']), Html::fa('unlink'), [
				'class' => 'btn btn-danger btn-fa unpair',
				'data-toggle' => 'tooltip',
				'data-placement' => 'top',
				'title' => 'Rozłącz konto'
			], false).($user->isVerified ? null : Html::a(Url::to(['user/verify']), Html::fa('check'), [
				'class' => 'btn btn-warning btn-fa verify',
				'data-toggle' => 'tooltip',
				'data-placement' => 'top',
				'title' => 'Zweryfikuj konto'
			], false))
		: Html::a(Url::to(['user/pair']), Html::fa('link').' Powiąż z kontem LoL', ['class' => 'btn btn-info btn-sm pair'], false)); ?>
		</div>
		
		<div class="team <?= $user->summonerName ? '' : 'inactive'?>">
			<?= Html::fa('users', true) ?>
			
			<?php			 
				
			if ($user->team)
			{
				if ($user->isMember)
				{
					echo $user->team->name.' ';
				}
				else
				{
					echo $user->team->name.' '.Html::tag('small', '(oczekujące)');
				}
				
				echo Html::a(Url::to(['user/leaveTeam']), Html::fa($user->isMember ? 'sign-out' : 'remove'), [
					'class' => 'btn btn-warning btn-fa '.($user->id == $user->team->ownerId ? 'btn-left' : null),
					'data-toggle' => 'tooltip',
					'data-placement' => 'top',
					'title' => $user->isMember ? 'Opuść drużynę' : 'Cofnij prośbę',
				], false);
				
				if ($user->id == $user->team->ownerId)
				{
					echo Html::a(Url::to(['team/remove', 'id' => $user->team->id]), Html::fa('remove'), [
						'class' => 'btn btn-danger btn-fa btn-right',
						'data-toggle' => 'tooltip',
						'data-placement' => 'top',
						'title' => 'Usuń drużynę'
					], false);
				}
			}
			else
			{
				if ($user->summonerName)
				{
					echo Html::a(Url::to('team/list'), Html::fa('plus').' Dołącz do drużyny', ['class' => 'btn btn-info btn-sm'], false);
				}
				else
				{
					echo 'Nie możesz dołączyć do drużyny, ponieważ nie powiązałeś swojego konta League of Legends.';
				}
			}
				
			?>
		</div>
		
	</div>
	
</div>

league/views/user/pair.php
<h1>Parowanie konta</h1>

<?php

$form = new Form($user);

echo $form->begin([
		'id' => 'user-lol-pair-form',
		'class' => 'form-wide form-horizontal', 
		'layout' => [
			'label' => 'col-xs-3', 
			'field' => 'col-xs-9', 
			'offset' => 'col-xs-offset-3'
		]
	]);
echo $form->field('summonerName')->text();

echo $form->end(true, 'Sparuj konto');


?>

league/views/user/signup.php
<?php

$form = new Form(new User);

$title = 'Zarejestruj się';
echo Html::tag('h1', $title);

echo $form->begin([
		'id' => 'signup-form',
		'class' => 'form-wide form-horizontal', 
		'layout' => [
			'label' => 'col-xs-2', 
			'field' => 'col-xs-10', 
			'offset' => 'col-xs-offset-2'
		]
	]);
echo $form->field('username')->text();
echo $form->field('password')->password();
echo $form->field('email')->text();
echo $form->field('firstName')->text();
echo $form->field('lastName')->text();
echo $form->field('school')->dropdown(App::$config['lo_list']);

echo Html::tag('div', 'Zakładając konto oświadczasz jednocześnie, że akceptujesz ogólny regulamin turnieju oraz regulamin rozgrywek League of Legends.', ['class' => 'col-xs-offset-2 terms'], false);

echo $form->end(true, 'Utwórz konto');

?>

league/views/user/uploadAvatar.php
<h1>Ustawianie awatara</h1>

<?php

$form = new Form($user);

echo $form->begin([
		'id' => 'user-avatar-form',
		'class' => 'form-wide form-inline', 
		'layout' => [
			'field' => 'col-xs-3', 
		],
		'enctype' => 'multipart/form-data',
	]);
echo $form->field('image')->file(['accept' => 'image/jpeg,image/png']);

echo $form->end(true, 'Zmień awatar');


?>

league/views/user/verify.php
<h1>Weryfikacja konta LoL</h1>
<div class="verify">
<p>Aby zweryfikować konto League of Legends, zmień nazwę jednej ze swoich stron na runy na kod wyświetlony poniżej. Gdy już to zrobisz, klinij przycisk.</p>
<div class="vcontainer">
	<div class="vkey"><?= $model->verificationKey ?></div>
	<a href="<?= Url::to(['user/verify', 'done' => true]) ?>"><div class="button"><?= Html::fa('check') ?></div></a>
</div>
</div>

league/views/user/view.php
<h1>Profil</h1>

<div class="row profile">
	
	<div class="col-lg-2 mb-3 mb-lg-0">
		
		<div class="avatar">
			
			<img src="<?= $user->avatarPath ?>" class="img-rounded"/>
			
		</div>
		
	</div>
	
	<div class="col-lg-10">
		
		<div class="name"><?= Html::fa('user', true).' '.$user->fullName ?></div>
		
		<div class="school"><?= Html::fa('graduation-cap', true).' '.$user->school ?></div>
		
		<div class="summoner <?= $user->isVerified ? '' : 'inactive'?>"><?= Html::fa('gamepad', true).' '.($user->isVerified 
		? $user->summonerName.Html::a("http://eune.op.gg/summoner/userName=$user->summonerName",Html::fa('external-link'), [], false)
		: 'Użytkownik nie powiązał swojego konta z League of Legends.') ?>
		</div>
		
		<div class="team <?= $user->isMember ? '' : 'inactive'?>">
			
			<?= Html::fa('users', true).' '.($user->isMember ? Html::a(Url::to(['team/view', 'id' => $user->team->id]), $user->team->name) : 'Użytkownik nie dołączył do żadnej drużyny.') ?>
			
		</div>
		
		<?php if (App::isAdmin()): ?>
		
		<div class="email">
			
			<?= Html::fa('envelope', true).' '.Html::a("mailto:$user->email", $user->email) ?>
			
		</div>
		
		<?= Html::a(Url::to(['admin/removeUser', 'id' => $user->id]), Html::fa('remove').' Usuń użytkownika', ['class' => 'btn btn-danger btn-sm'], false) ?>
		 
		<?php endif; ?>
		
		
		<?php if(App::$user->id == $user->id): ?>
		
			<div class="edit">
				
				<?= Html::a(Url::to(['user/edit', 'id' => App::$user->id]), Html::fa('pencil').' Edytuj profil', ['class' => 'btn btn-warning btn-sm'], false) ?>
			
			</div>
		
		<?php endif; ?>
		
	</div>
	
</div>